### ISSUE TITLE
Some questions about obtaining the offset

### ISSUE THREAD

**Issue by smile-struggler** [roywang021/UMK#2]
Hello author, thank you for your excellent work! However, I encountered some issues during reproduction and would like to ask for your guidance.

In ‘minigpt_utils/prompt_wrapper.py’, the text and image embeddings are alternately placed within the context embedding. 
```python
else: # mix
    s = t = 0
    mixed_embs = []
    while(s<num_text_segs and t<num_img_segs):
        mixed_embs.append(text_embs[s])
        mixed_embs.append(img_embs[t])
        s,t = s+1,t+1
    if s<num_text_segs: mixed_embs += text_embs[s:]
    if t<num_img_segs: mixed_embs += img_embs[t:]
```

However, the offset is directly computed by splitting the item with prompt_segs = re.split('<ImageHere>|<adv_split_start>|</adv_split_end>', item), and then adding the lengths of the first two text segments. 
```python
prompt_segs =re.split('<ImageHere>|<adv_split_start>|</adv_split_end>',item)
seg_tokens = [
    self.model.llama_tokenizer(
        seg, return_tensors="pt", add_special_tokens=i == 0).to(self.device).input_ids

    for i, seg in enumerate(prompt_segs)
]
item_offset=seg_tokens[0].shape[1]+seg_tokens[1].shape[1]
```
But in this case, it seems that **the image tokens are not taken into account**. Could you kindly clarify this for me when you have a moment? Thank you!

**Comment by roywang021** [comment]
Thank you for pointing out this issue.  You're right – when computing the offset for the adv suffix, we should indeed account for the length of the image embeddings.  Apologies for the oversight in the version we uploaded;  it contained a bug related to this issue.
We have already fixed it and updated the code accordingly.  Please feel free to try the new version and let us know if you encounter any further issues.
Thanks again for your careful observation and your patience!

**Comment by smile-struggler** [comment]
Thank you for the quick fix and clarification! I’ll try the new version and appreciate your help!
